apiVersion: skaffold/v2alpha2
kind: Config
build:
  artifacts:
  - image: nginx-skaffold
    context: .
    docker:
      dockerfile: Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s-*