name: Skaffold Run

on:
  push:
    branches:
      - .
  pull_request:
    branches:
      - main

jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: test-masking
      - name: bash-version
        run: |
          echo "${{ github.actor }}:${{ secrets.VERY_SECRET }}"
          # Mask the github.actor value
           echo "::add-mask::$MY_NAME"
          # Use the masked value in your commands or scripts
            echo "Masked actor: $MY_NAME"
            #./test_mask.sh test_mask $MY_NAME