name: Skaffold Run

on:
  push:
    branches:
      - .
  pull_request:
    branches:
      - main

jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    steps:
      - name: bash-version
        env:
          MY_NAME: "Mona The Octocat"
        run: echo "::add-mask::$MY_NAME"