name: Skaffold Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/

    - name: Start Minikube
      run: |
        minikube start

    - name: Install Skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        chmod +x skaffold
        sudo mv skaffold /usr/local/bin/
    
    - name: Cache Skaffold
      uses: actions/cache@v2
      with:
        path: |
          skaffold_cache/cache
        key: sk-${{ github.sha }}
        restore-keys: |
          sk-${{ github.sha }}
          sk-
    - name: Run Skaffold
      run: |
        cat skaffold_cache/cache || true
        skaffold run --cache-file='skaffold_cache/cache'
        echo "Skaffold Cache Created"
        cat skaffold_cache/cache || true
    - name: Cache Cypress dependencies
      id: cypress-cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/Cypress
          node_modules
        key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - name: install cypress
      if: steps.cypress-cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: Run Cypress test
      run: |
        npm run test
