name: Skaffold Run

on:
  push:
    branches:
      - .
  pull_request:
    branches:
      - main

jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    env:
          MY_NAME: "Mona The Octocat"
    steps:
      - name: bash-version
        run: |
          # Mask the github.actor value
           echo "::add-mask::$MY_NAME"
          # Use the masked value in your commands or scripts
            echo "Masked actor: $MY_NAME"